---
title: '`r params$title`'
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    theme: flatly
    highlight: tango
    fig_width: 9
params:
  title:
    value: "Title"
  query:
    value: "select * from data where substr(postcode, 1, 3) = 'M5A'"
---

```{r setup, message=FALSE, results='hide', echo=FALSE , warning=FALSE}
library(RPostgreSQL)
library(data.table)
library(magrittr)
library(lubridate)
library(ggplot2)
library(DT)
source('dlin.R')

options(datatable.print.nrows=1000, width=120)

drv = dbDriver('PostgreSQL')
conn = dbConnect(drv, dbname='postgres')
d = dbGetQuery(conn, "select * from data where substr(postcode, 1, 3) = 'M5A'") %>% setDT
postal = dbReadTable(conn, 'postal') %>% setDT


d[, date := parse_date_time(date, '%Y-%m-%d')]
d[, arrive := ymd_hms(paste(date, arrive, sep=' '))]
d[, depart := ymd_hms(paste(date, depart, sep=' '))]
d[, fiscal_year := year(date + days(120))]

most_recent_fy = max(d$fiscal_year)
fyname = paste0('FY', substr(most_recent_fy, 3, 4))

idv = c('date', 'trans_type', 'route_desc', 'stop_type', 'source_type', 'driver', 'donor_id', 'arrive', 'depart', 'quality', 'zero_lbs', 'postcode', 'fiscal_year')
mav = c('bread', 'baked', 'dairy', 'produce', 'protein', 'prepared', 'bev_juice', 'bev_other', 'snack', 'non_perish', 'non_food')

dmelt = melt(d, variable.name = 'food_type', value.name = 'amount', id.vars = idv, measure.vars = mav)[amount > 0]
dmelt[, fsa := substr(postcode, 1, 3)]

top_types = dmelt[stop_type == 'Delivery' & fiscal_year == most_recent_fy, sum(amount), by=food_type][
  ,V2 := V1 / sum(V1)][order(-V1)][, value := V1 * 2.5]

top_types[, food_type := as.character(food_type)]
top_types[, high_nutrient := FALSE]
top_types[food_type %in% c('dairy','protein','produce'), high_nutrient := TRUE]
```

## Charts

```{r echo=FALSE, message=FALSE, warning=FALSE}

dmelt[, sum(amount * 2.5 / 1e6), by=.(floor_date(date, unit='quarter'), stop_type)] %>% 
  ggplot(aes(x = floor_date, y = V1, col=stop_type)) + geom_line() + geom_point() +
  labs(title = 'Total Value of Food Delivered by Quarter', x = 'Date',
       y = 'Dollar Value ($M)') + theme_dlin()

d[, .( Perishable = sum(bread + baked + dairy + produce + protein + prepared + bev_juice + bev_other + snack) / 
    sum(bread + baked + dairy + produce + protein + prepared + bev_juice + bev_other + snack + non_perish + non_food),
    `High Nutrient` = sum(dairy + produce + protein) / 
      sum(bread + baked + dairy + produce + protein + prepared + bev_juice + bev_other + snack + non_perish + non_food)), 
  by=.(floor_date(date, unit='quarter'), stop_type)] %>% 
  melt(id.vars = 1:2, measure.vars = 3:4) %>% 
  ggplot(aes(x = floor_date, y = value, col = variable)) + 
  facet_grid(~stop_type) + geom_line() + geom_point() + 
  labs(title = 'Ratios', col = NULL, x = 'Month', y = NULL) + theme_dlin()


ggplot(top_types, aes(x = food_type, weight = value / 1e3, fill = high_nutrient)) + 
  geom_bar() + theme_dlin() + scale_x_discrete(limits = top_types$food_type) +
  geom_text(aes(y = value / 2e3, label = sprintf('$%.1fK\n(%.1f%%)', value / 1e3, V2 * 100))) + 
  theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1)) + 
  labs(x = 'Type of Food', y = 'Value of Donations ($M)', 
       title = paste0('Types of Food Donated for ', fyname),
       fill = 'High Nutrient')

datatable(top_types[,.(`Food Type` = food_type, `Total Value` = value, `Percent of Deliveries` = V2, `Pounds of Food` = V1)]) %>% formatPercentage(3, 1) %>% formatCurrency(2, '$')

day_order = c('Sun','Mon','Tue','Wed','Thu','Fri','Sat')

dmelt[, sum(amount), by=.(stop_type, weekdays(date, abbreviate = T), hour(arrive))] %>% 
  ggplot(aes(weekdays, hour)) + 
  geom_tile(aes(fill = V1), col = 'white', size=1.1) + theme_dlin() +
  scale_x_discrete(expand = c(0, 0), limits=day_order) + 
  scale_y_reverse(breaks=seq(8,19,4)) +
  labs(title = 'Pickup and Delivery Times', x = 'Day of Week', 
       y = 'Hour of Day', fill = 'Pounds') + 
  facet_grid(~stop_type, ) + theme(panel.margin = unit(2, "lines")) +
  scale_fill_distiller(palette = 'Oranges', direction = 1)

```
